(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var n=this||self,p="closure_uid_"+(1E9*Math.random()>>>0),da=0,ea=Date.now;function w(a){w[" "](a);return a}w[" "]=function(){};var fa=(a,b)=>"&adurl="==a.substring(a.length-7)?a.substring(0,a.length-7)+b+"&adurl=":a+b;let x=n.dicnf||{};function ha(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)};var ia=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function y(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{w(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}function ja(a,b){if(a)for(const c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)}let z=[];const B=()=>{const a=z;z=[];for(const b of a)try{b()}catch(c){}}; 
var ka=(a,b)=>{"complete"===a.readyState||"interactive"===a.readyState?(z.push(b),1==z.length&&(window.Promise?Promise.resolve().then(B):window.setImmediate?setImmediate(B):setTimeout(B,0))):a.addEventListener("DOMContentLoaded",b)};const E=["FRAME","IMG","IFRAME"],la=/^[01](px)?$/;function ma(a){return"IMG"!=a.tagName||!a.complete||a.naturalWidth&&a.naturalHeight?la.test(a.getAttribute("width"))&&la.test(a.getAttribute("height")):!0} 
function na(a,b){var c;if(a="string"===typeof a?document.getElementById(a):a){c||(c=(k,q,r)=>{k.addEventListener(q,r)});var d=!1,e=k=>{d||(d=!0,b(k))};for(var g=0;g<E.length;++g)if(E[g]==a.tagName){var f=3;var m=[a];break}m||(m=a.querySelectorAll(E.join(",")),f=2);var l=0;a=!1;for(g=0;g<m.length;g++){const k=m[g];if(!ma(k)){if("IMG"==k.tagName)var h=k.naturalWidth&&k.naturalHeight?!0:!1;else try{h="complete"===(k.readyState?k.readyState:k.contentWindow&&k.contentWindow.document&&k.contentWindow.document.readyState)? 
!0:!1}catch(q){h=!1}h?a=!0:(l++,c(k,"load",()=>{l--;l||e(f)}))}}m=null;if(0===l&&!a&&"complete"===n.document.readyState)f=5;else if(l||!a){c(n,"load",()=>{e(4)});return}e(f)}};function oa(a){const b=a.length;let c=0;return new F(d=>{if(0==b)d([]);else{const e=[];for(let g=0;g<b;++g)G(a[g],f=>{e[g]=f;++c==b&&d(e)})}})}function pa(){let a;const b=new F(c=>{a=c});return new qa(b,a)}function G(a,b){new F(c=>{ra(a,d=>{c(b(d))})})}function sa(a,b){if(!a.b)if(b instanceof F)G(b,c=>{sa(a,c)});else{a.b=!0;a.c=b;for(b=0;b<a.a.length;++b)ra(a,a.a[b]);a.a=[]}}function ra(a,b){a.b?b(a.c):a.a.push(b)}class F{constructor(a){this.b=!1;this.a=[];a(b=>{sa(this,b)})}} 
var qa=class{constructor(a,b){this.b=a;this.a=b}};function H(a){return{visible:1,hidden:2,prerender:3,preview:4,unloaded:5}[a.visibilityState||a.webkitVisibilityState||a.mozVisibilityState||""]||0}function ta(a){let b;a.visibilityState?b="visibilitychange":a.mozVisibilityState?b="mozvisibilitychange":a.webkitVisibilityState&&(b="webkitvisibilitychange");return b};function I(a,b){a.google_image_requests||(a.google_image_requests=[]);const c=a.document.createElement("img");c.src=b;a.google_image_requests.push(c)}var ua=(a,b)=>{var c;if(c=a.navigator)c=a.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&a.navigator.sendBeacon?a.navigator.sendBeacon(b):I(a,b)};let J=null;function va(a,b){/(google|doubleclick).*\/pagead\/adview/.test(b)&&(b=fa(b,`&vis=${H(a.a)}`));G(a.c,()=>{var c=a.f,d=b;x.atsb?ua(c,d):I(c,d)})}function wa(a){const b=[];if(x.umi){const c=new F(d=>{a.b=d});b.push(c)}if(x.ebrpfa){const c=pa();b.push(c.b);ka(a.a,()=>{na(a.a.body,c.a)})}3==H(a.a)&&3==H(a.a)&&b.push(xa(a));a.c=oa(b)} 
function xa(a){return new F(b=>{const c=ta(a.a);if(c){var d=()=>{if(3!=H(a.a)){var e=a.a;e.removeEventListener&&e.removeEventListener(c,d,!1);b()}};J&&(d=J(521,d));ha(a.a,c,d)}})}class K{constructor(){this.a=n.document;this.f=n;this.b=null;wa(this)}}(function(){var a=K;a.j=void 0;a.m=function(){return a.j?a.j:a.j=new a}})();let L=0;var Ca=document,M=window;var N={};var Da=class{},Ea=class extends Da{constructor(a,b){super();if(b!==N)throw Error("Bad secret");this.a=a}toString(){return this.a}};new Ea("about:blank",N);new Ea("about:invalid#zTSz",N);var Fa=!!window.google_async_iframe_id;let O=Fa&&window.parent||window;class Ga{constructor(a,b,c={}){this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c}};const Ha=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/;var Ia=class{constructor(a,b){this.a=a;this.b=b}},Ja=class{constructor(a,b,c,d,e){this.url=a;this.o=!!d;this.depth="number"===typeof e?e:null}};function P(a,b){const c={};c[a]=b;return[c]}function Ka(a,b,c,d,e){const g=[];ja(a,function(f,m){(f=La(f,b,c,d,e))&&g.push(m+"="+f)});return g.join(b)} 
function La(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){const g=[];for(let f=0;f<a.length;f++)g.push(La(a[f],b,c,d+1,e));return g.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Ka(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}function Ma(a){if(!a.c)return a.g;let b=1;for(const c in a.b)b=c.length>b?c.length:b;return a.g-a.c.length-b-a.f.length-1} 
function Na(a,b,c,d){b=b+"//"+c+d;var e=Ma(a)-d.length;if(0>e)return"";a.a.sort(function(g,f){return g-f});d=null;c="";for(let g=0;g<a.a.length;g++){const f=a.a[g],m=a.b[f];for(let l=0;l<m.length;l++){if(!e){d=null==d?f:d;break}let h=Ka(m[l],a.f,a.h);if(h){h=c+h;if(e>=h.length){e-=h.length;b+=h;c=a.f;break}d=null==d?f:d}}}e="";a.c&&null!=d&&(e=c+a.c+"="+(a.l||d));return b+e} 
class Q{constructor(a,b,c,d,e){this.g=c||4E3;this.f=a||"&";this.h=b||",$";this.c=void 0!==d?d:"trn";this.l=e||null;this.b={};this.i=0;this.a=[]}};function Oa(a,b,c,d,e){if((d?a.a:Math.random())<(e||a.c))try{let g;c instanceof Q?g=c:(g=new Q,ja(c,(m,l)=>{var h=g,k=h.i++;m=P(l,m);h.a.push(k);h.b[k]=m}));const f=Na(g,a.h,a.f,a.g+b+"&");f&&(a.b?ua(n,f):I(n,f))}catch(g){}}class Pa{constructor(a,b,c,d,e=!1){this.h=a;this.f=b;this.g=c;this.c=d;this.b=e;this.a=Math.random()}};let R=null;var Qa=()=>{const a=n.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):ea()},Ra=()=>{const a=n.performance;return a&&a.now?a.now():null};class Sa{constructor(a,b,c,d=0,e){this.label=a;this.type=b;this.value=c;this.duration=d;this.uniqueId=Math.random();this.slotId=e}};const S=n.performance,Ta=!!(S&&S.mark&&S.measure&&S.clearMarks),T=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=Ta){var b;if(null===R){R="";try{a="";try{a=n.top.location.hash}catch(c){a=n.location.hash}a&&(R=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=R;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function Ua(a){a&&S&&T()&&(S.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),S.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class Va{constructor(a,b){this.b=[];this.c=b||n;let c=null;b&&(b.google_js_reporting_queue=b.google_js_reporting_queue||[],this.b=b.google_js_reporting_queue,c=b.google_measure_js_timing);this.a=T()||(null!=c?c:Math.random()<a)}start(a,b){if(!this.a)return null;const c=Ra()||Qa();a=new Sa(a,b,c);b=`goog_${a.label}_${a.uniqueId}_start`;S&&T()&&S.mark(b);return a}};function U(a){let b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);let c;for(;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(c){}}return b} 
function Wa(a,b,c,d){let e,g;try{if(a.a&&a.a.a){g=a.a.start(b.toString(),3);e=c();var f=a.a;c=g;if(f.a&&"number"===typeof c.value){var m=Ra()||Qa();c.duration=m-c.value;var l=`goog_${c.label}_${c.uniqueId}_end`;S&&T()&&S.mark(l);!f.a||2048<f.b.length||f.b.push(c)}}else e=c()}catch(h){f=a.h;try{Ua(g),f=a.i(b,new Ga(h,{message:U(h)}),void 0,d)}catch(k){a.f(217,k)}if(!f)throw h;}return e}function V(a,b,c,d){var e=W;return(...g)=>Wa(e,a,()=>b.apply(c,g),d)} 
class Xa{constructor(a,b,c,d=null){this.g=a;this.l=b;this.h=c;this.b=null;this.i=this.f;this.a=d;this.c=!1}f(a,b,c,d,e){e=e||this.l;let g;try{const t=new Q;var f=t;f.a.push(1);f.b[1]=P("context",a);b.error&&b.meta&&b.id||(b=new Ga(b,{message:U(b)}));if(b.msg){f=t;var m=b.msg.substring(0,512);f.a.push(2);f.b[2]=P("msg",m)}var l=b.meta||{};b=l;if(this.b)try{this.b(b)}catch(A){}if(d)try{d(b)}catch(A){}d=t;l=[l];d.a.push(3);d.b[3]=l;{{d=n;l=[];b=null;let Z;do{var h=d;if(y(h)){var k=h.location.href;b= 
h.document&&h.document.referrer||null;Z=!0}else k=b,b=null,Z=!1;l.push(new Ja(k||"",h,Z));try{d=h.parent}catch(C){d=null}}while(d&&h!=d);for(let C=0,ya=l.length-1;C<=ya;++C)l[C].depth=ya-C;h=n;if(h.location&&h.location.ancestorOrigins&&h.location.ancestorOrigins.length==l.length-1)for(k=1;k<l.length;++k){var q=l[k];q.url||(q.url=h.location.ancestorOrigins[k-1]||"",q.o=!0)}var r=l}let A=new Ja(n.location.href,n,!0,!1);h=null;const aa=r.length-1;for(q=aa;0<=q;--q){var u=r[q];!h&&Ha.test(u.url)&&(h= 
u);if(u.url&&!u.o){A=u;break}}u=null;const ab=r.length&&r[aa].url;0!=A.depth&&ab&&(u=r[aa]);g=new Ia(A,u,h)}if(g.b){r=t;var v=g.b.url||"";r.a.push(4);r.b[4]=P("top",v)}var ba={url:g.a.url||""};if(g.a.url){var ca=g.a.url.match(ia),D=ca[1],za=ca[3],Aa=ca[4];v="";D&&(v+=D+":");za&&(v+="//",v+=za,Aa&&(v+=":"+Aa));var Ba=v}else Ba="";D=t;ba=[ba,{url:Ba}];D.a.push(5);D.b[5]=ba;Oa(this.g,e,t,this.c,c)}catch(t){try{Oa(this.g,e,{context:"ecmserr",rctx:a,msg:U(t),url:g&&g.a.url},this.c,c)}catch(A){}}return this.h}} 
;let Ya,W;if(Fa&&!y(O)){let a="."+Ca.domain;try{for(;2<a.split(".").length&&!y(O);)Ca.domain=a=a.substr(a.indexOf(".")+1),O=window.parent}catch(b){}y(O)||(O=window)}const X=O,Y=new Va(1,X);var Za=()=>{X.google_measure_js_timing||(Y.a=!1,Y.b!=Y.c.google_js_reporting_queue&&(T()&&Array.prototype.forEach.call(Y.b,Ua,void 0),Y.b.length=0))};Ya=new Pa("http:"===M.location.protocol?"http:":"https:","pagead2.googlesyndication.com","/pagead/gen_204?id=",.01);"number"!==typeof X.google_srt&&(X.google_srt=Math.random()); 
var $a=X.google_srt;0<=$a&&1>=$a&&(Ya.a=$a);W=new Xa(Ya,"jserror",!0,Y); 
W.b=a=>{var b=M.jerExpIds;if(Array.isArray(b)&&0!==b.length){var c=a.eid;if(c){c=[...c.split(","),...b];b={};for(var d=0,e=0;e<c.length;){var g=c[e++];var f=g;var m=typeof f;f="object"==m&&null!=f||"function"==m?"o"+(Object.prototype.hasOwnProperty.call(f,p)&&f[p]||(f[p]=++da)):(typeof f).charAt(0)+f;Object.prototype.hasOwnProperty.call(b,f)||(b[f]=!0,c[d++]=g)}c.length=d;a.eid=c.join(",")}else a.eid=b.join(",")}0!==L&&(a.jc=String(L));(c=M.jerUserAgent)&&(a.useragent=c)};W.c=!0; 
"complete"==X.document.readyState?Za():Y.a&&ha(X,"load",()=>{Za()});L=40;J=(a,b,c,d)=>V(a,b,c,d);window.vu=V(492,function(a){x.ebrpfa&&(a=fa(a,"&cbvp=2"));a=a.replace("&amp;","&");va(K.m(),a)},void 0,void 0);window.vv=V(494,function(){const a=K.m();if(!a.b)throw Error("aiv::err");a.b()},void 0,void 0);}).call(this);
